// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyectoie.Web.Data;

namespace Proyectoie.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201110204610_AddEmpleados")]
    partial class AddEmpleados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyectoie.Web.Data.Entities.EmpleadosEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<string>("Cargo")
                        .IsRequired();

                    b.Property<string>("Departamento")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("ExtensionTelefono");

                    b.Property<string>("LogoPath");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Proyectoie.Web.Data.Entities.SucursalEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad")
                        .IsRequired();

                    b.Property<string>("Direccion")
                        .IsRequired();

                    b.Property<int?>("EmpleadosEntidadId");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("Telefono")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EmpleadosEntidadId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Proyectoie.Web.Data.Entities.SucursalEntidad", b =>
                {
                    b.HasOne("Proyectoie.Web.Data.Entities.EmpleadosEntidad")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpleadosEntidadId");
                });
#pragma warning restore 612, 618
        }
    }
}
